"""empty message

Revision ID: 111c9007fab8
Revises: 0aea20d5d6fc
Create Date: 2019-01-27 01:58:27.071818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111c9007fab8'
down_revision = '0aea20d5d6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plays', 'count')
    # ### end Alembic commands ###
