"""Spotify id to string

Revision ID: 3196bdfa1ac8
Revises: d7e483fe59b7
Create Date: 2019-01-27 04:39:06.701693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3196bdfa1ac8'
down_revision = 'd7e483fe59b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'spotify_id', _type=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'spotify_id', _type=sa.Integer)
    # ### end Alembic commands ###
