"""fixed nullables

Revision ID: d7e483fe59b7
Revises: 111c9007fab8
Create Date: 2019-01-27 03:32:03.159717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7e483fe59b7'
down_revision = '111c9007fab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('songs', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artists', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
